---
- name: Download 1Password for macOS.
  ansible.builtin.get_url:
    url: "https://downloads.1password.com/mac/1Password.zip"
    dest: "{{ lookup('env', 'HOME') }}/Downloads/1Password.zip"

- name: Install 1Password for macOS.
  ansible.builtin.command: "osascript files/1password_installer.applescript"
  args:
    creates: "/Applications/1Password.app"

- name: Download 1Password CLI for macOS.
  ansible.builtin.get_url:
    url: "https://cache.agilebits.com/dist/1P/op2/pkg/v{{ package_versions.onepassword }}/op_apple_universal_v{{ package_versions.onepassword }}.pkg"
    dest: "{{ lookup('env', 'HOME') }}/Downloads/op_apple_universal.pkg"

- name: Install 1Password CLI for macOS.
  ansible.builtin.command: "osascript files/1password_cli_installer.applescript"
  args:
    creates: "/usr/local/bin/op"
