---
- name: Download and install 1Password CLI.
  ansible.builtin.include_tasks: "1password_{{ ansible_facts.system }}.yaml"

- name: Install 1Password CLI shell completion for Bash.
  ansible.builtin.lineinfile:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.bashrc"
    line: 'source <(op completion bash) # 1Password CLI'
    state: present
  ignore_errors: true

- name: Install 1Password CLI shell completion for Zsh.
  ansible.builtin.lineinfile:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.zshrc"
    line: 'eval "$(op completion zsh)"; compdef _op op # 1Password CLI'
    state: present
  ignore_errors: true
