---
- name: Download Tailscale for macOS.
  ansible.builtin.get_url:
    url: "https://pkgs.tailscale.com/stable/Tailscale-latest-macos.pkg"
    dest: "{{ lookup('env', 'HOME') }}/Downloads/Tailscale-latest-macos.pkg"

- name: Install Tailscale for macOS.
  ansible.builtin.command: "osascript files/tailscale_installer.applescript"
  args:
    creates: "/Applications/Tailscale.app"
